//🗺️ Physical Interface Mapping (FPGA Pin Out Configuration)
//The following pin mappings are configured via the system constraints file (.xdc) targeting the physical interfaces on the Anmaya Artix-7 board:

create_clock -period 41.667 -name sys_clk [get_ports clk_24mhz]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN D5 [get_ports {led[0]}]
set_property PACKAGE_PIN A3 [get_ports {led[1]}]
set_property PACKAGE_PIN B4 [get_ports {led[2]}]
set_property PACKAGE_PIN A4 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]
set_property PACKAGE_PIN K5 [get_ports buzzer]
set_property PACKAGE_PIN D13 [get_ports clk_24mhz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_24mhz]
set_property PACKAGE_PIN T2 [get_ports dht_data]
set_property IOSTANDARD LVCMOS33 [get_ports dht_data]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_pin]
set_property PACKAGE_PIN R3 [get_ports uart_rx]
set_property PACKAGE_PIN T3 [get_ports uart_tx_pin]
set_property PACKAGE_PIN A13 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN C7 [get_ports sw_buzzer_en]
set_property PACKAGE_PIN E6 [get_ports led_buzzer_status]
set_property IOSTANDARD LVCMOS33 [get_ports led_buzzer_status]
set_property IOSTANDARD LVCMOS33 [get_ports sw_buzzer_en]
